#!/bin/bash

# wrap-dbus is a script for a semi-private session bus on headless logins
# Copyright (C) 2012 Jens Georg <mail@jensge.org>
#
# This file is part of Rygel.
#
# Rygel is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# Rygel is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

[ -z $1 ] && exit 127

command=$(shift 1)

pid=$(grep DBUS_SESSION_BUS_PID $HOME/.dbusrc | cut -f2 -d= | sed -e 's,;,,')
cmdline="/proc/$pid/cmdline"
if [ -e $cmdline ]
then
    if grep -q "dbus-daemon" $cmdline; then
        . $HOME/.dbusrc
        exec $command $*
    fi
fi

dbus=($(dbus-daemon --fork --session --print-address 1 --print-pid 1))
echo DBUS_SESSION_BUS_ADDRESS="'${dbus[0]}'" > $HOME/.dbusrc
echo export DBUS_SESSION_BUS_ADDRESS >> $HOME/.dbusrc
echo DBUS_SESSION_BUS_PID=${dbus[1]} >> $HOME/.dbusrc
. $HOME/.dbusrc
exec $command $*
